<a href="https://colab.research.google.com/github/a9x26j8i/PythonLearning/blob/master/numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

a = np.arange(1, 10).reshape(3,3).T

print(a)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
